/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RacesNewRouteImport } from './routes/races.new'
import { Route as RacesRaceIdRouteImport } from './routes/races.$raceId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesNewRoute = RacesNewRouteImport.update({
  id: '/races/new',
  path: '/races/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesRaceIdRoute = RacesRaceIdRouteImport.update({
  id: '/races/$raceId',
  path: '/races/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/races/new': typeof RacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/races/new': typeof RacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/races/new': typeof RacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/races/$raceId' | '/races/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/races/$raceId' | '/races/new'
  id: '__root__' | '/' | '/history' | '/races/$raceId' | '/races/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  RacesRaceIdRoute: typeof RacesRaceIdRoute
  RacesNewRoute: typeof RacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/new': {
      id: '/races/new'
      path: '/races/new'
      fullPath: '/races/new'
      preLoaderRoute: typeof RacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/$raceId': {
      id: '/races/$raceId'
      path: '/races/$raceId'
      fullPath: '/races/$raceId'
      preLoaderRoute: typeof RacesRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  RacesRaceIdRoute: RacesRaceIdRoute,
  RacesNewRoute: RacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
